### ISSUE TITLE
JPetRawSignal.h - duplicated method

### ISSUE THREAD

**Issue by Alvarness** [JPETTomography/j-pet-framework#54]
Just saw this - there are two methods for returning number of points on edge:

int getNumberOfPoints(JPetSigCh::EdgeType edge) const;
and
inline int getNumberOfLeadingEdgePoints(void) const
inline int getNumberOfTrailingEdgePoints(void) const

We should keep one of them (most likely first)

**Comment by wkrzemien** [comment]
Ok, I dont't if it was intended ? @alekgajos ?

**Comment by alekgajos** [comment]
It may be that one of this approaches was added later and the former was not removed. I would not strictly call this duplication but I do not recall if this was really intended and we may remove the last two methods.

**Comment by Alvarness** [comment]
Also, as:
a) Grzesiek said
b) I checked (and as far it is consistent
number of leading and trailing points is the same (if there is leading edge points we always have corresponding trailing edge point). So maybe change method to getNumberOfEgdePoints()?

**Comment by wkrzemien** [comment]
I would - as a sanity check if somebody wants- leave the first method with both options.
So let's say that we remove the last two methods.
@Alvarness  could prepare a small PR just with those last two methods removed? One needs to cross-check tests and other parts of course.

**Comment by wkrzemien** [comment]
.Solved with  #59
