### ISSUE TITLE
Methods returning maps - important issue

### ISSUE THREAD

**Issue by Alvarness** [JPETTomography/j-pet-framework#55]
There are several methods that are returning maps (especially in JPetRawSignal). That means each key has only one value (ex. one threshold number have one corresponding time) - and that assumption is not correct if we want to analyze whole signals and not only last points in time window .

This is really important issue in JPetRawSignal and might be a problem in other classes (haven't checked it yet).

Proposition is: change std::map to std::unordered_multimap (it's faster) or std::multimap (if we want to have already sorted entries)

**Comment by alekgajos** [comment]
I do not understand. JPetRawSignal should have no more than one time per threshold per edge. If there is more than one, this is not a single signal and it should not be contained in one object but in several instances of them.

**Comment by Alvarness** [comment]
Ok, point taken.

I'm treating everything on one photomultiplier in one time window as "signal" and then divide them into different signals (without creating temporary container). But fact - may way of thinking was incorrect - issue can be closed.

**Comment by alekgajos** [comment]
Ok, so this was a semantical issue;-) In principle a signal in the Framework is understood as a set of times at thresholds already selected as belonging to a single electric pulse from a PMT.
